# .github/workflows/deploy.yml
name: Build and Deploy to GitHub Pages

on:
  # Triggers on push to the main branch when ANY relevant files change
  push:
    branches: [ main ]
    paths:
      # Frontend source code that requires a rebuild
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      # Data files that require the app to be redeployed with the new data
      - 'analysis/**'
      - 'snapshots/**'
      - 'hashes.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # Use npm ci for faster, more reliable installs in CI

    - name: Build React app
      run: npm run build
      env:
        # This prevents the build from failing on non-critical warnings, but consider fixing them.
        CI: false

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # This tells the action to deploy the contents of the 'build' folder
        publish_dir: ./build
        # The branch the action should deploy to.
        publish_branch: gh-pages
