# .github/workflows/update_checker.yml
name: Check for Updates, Build, and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'policy_sets.json' 

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Clean up old logs
      run: |
        echo "Deleting logs older than 365 days..."
        find logs/ -type f -mtime +365 -exec echo "Deleting {}" \; -delete
        echo "Cleanup complete."

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- New Debugging Step ---
    - name: Verify Secrets are Loaded
      run: |
        echo "--- Verifying secrets ---"
        if [ -n "${{ secrets.PROXY_HOST }}" ]; then
          echo "PROXY_HOST secret: Loaded"
        else
          echo "PROXY_HOST secret: NOT FOUND"
        fi
        if [ -n "${{ secrets.PROXY_USER }}" ]; then
          echo "PROXY_USER secret: Loaded"
        else
          echo "PROXY_USER secret: NOT FOUND"
        fi
        if [ -n "${{ secrets.PROXY_PASS }}" ]; then
          echo "PROXY_PASS secret: Loaded"
        else
          echo "PROXY_PASS secret: NOT FOUND"
        fi
        echo "-------------------------"

    - name: Run update script
      id: run_script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PROXY_HOST: ${{ secrets.PROXY_HOST }}
        PROXY_USER: ${{ secrets.PROXY_USER }}
        PROXY_PASS: ${{ secrets.PROXY_PASS }}
      run: python main.py

    - name: Commit and push if changed
      id: commit_push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add analysis/ snapshots/ hashes.json policy_sets.json
        git add -f logs/
        
        if git diff --staged --quiet; then
          echo "No content changes detected by the script."
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Update content snapshots and analysis [$(date +'%Y-%m-%d %H:%M:%S UTC')]"
          git pull --rebase
          git push
          echo "Content changes committed and pushed."
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      run: |
        npm ci || (echo "npm ci failed, falling back to npm install" && npm install)

    - name: Build React app
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      run: npm run build
      env:
        CI: true
        GENERATE_SOURCEMAP: false

    - name: Copy data files to build directory
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      run: |
        echo "Copying data files to build directory..."
        mkdir -p build/analysis build/snapshots build/logs
        cp hashes.json build/
        cp policy_sets.json build/
        find analysis -mindepth 1 -print0 | xargs -0 -I {} cp -r {} build/analysis/ || echo "No analysis files to copy"
        find snapshots -mindepth 1 -print0 | xargs -0 -I {} cp -r {} build/snapshots/ || echo "No snapshot files to copy"
        find logs -mindepth 1 -print0 | xargs -0 -I {} cp -r {} build/logs/ || echo "No log files to copy"
        
    - name: Setup Pages
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'
        
    - name: Deploy to GitHub Pages
      if: steps.commit_push.outputs.changes_detected == 'true' || github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4
