# .github/workflows/update_checker.yml
name: Check for Website Updates

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on a schedule (every day at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-updates:
    runs-on: ubuntu-latest

    # IMPORTANT: Add permissions for the job to be able to write to the repo.
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        # We need to fetch all history to be able to push back to the repo
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      # The script is now non-interactive and safe to run in an action.
      run: python main.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Only add the specific files/directories that should be updated
        git add analysis/ snapshots/ hashes.json
        
        # Check if there are any staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update content snapshots and analysis [$(date +'%Y-%m-%d %H:%M:%S UTC')]"
          git push
          echo "Changes committed and pushed."
        fi
